-- SQL 에는 4개의 종류가 있음
-- 1. DDL(definition) : CAD
-- 2. DML(manipulation) : CRUD
-- 3. DCL(control)
-- 4. TCL(TX control)

-- DDL
-- CREATE : 테이블 생성
-- ALTER : 테이블 수정
-- DROP : 테이블 삭제
-- DML
-- C : insert 자료 추가
-- R : select 자료 검색
-- U : update 자료 수정
-- D : delete 자료 삭제